DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS GOODS_DETAIL;
DROP TABLE IF EXISTS GOODS;
DROP TABLE IF EXISTS USER;

 CREATE TABLE GOODS (
	GOODS_ID INT(10),
	NAME  VARCHAR(40),
	PROVIDER VARCHAR(40),
	PRICE INT(40),
	SHIPPING_METHOD VARCHAR(40),
	SHIPPING_PRICE VARCHAR(40),
	REG_DTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	MOD_DTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (GOODS_ID)
 );
 
 CREATE TABLE GOODS_DETAIL (
	GOODS_DETAIL_ID INT(10),
	COLOR VARCHAR(20),
	SIZE VARCHAR(10),
	STOCK INT(20),
	PROVIDER VARCHAR(40),
	GOODS_ID INT(10),
	REG_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPD_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (GOODS_DETAIL_ID, GOODS_ID),
	FOREIGN KEY (GOODS_ID) REFERENCES GOODS (GOODS_ID)
 );

 CREATE TABLE USER (
	USER_ID INT(10),
	REG_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPD_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (USER_ID)
 );

 CREATE TABLE CART (
 	CART_ID INT(10) AUTO_INCREMENT,
 	USER_ID INT(10),
	GOODS_ID INT(10),
	GOODS_DETAIL_ID INT(10),
	REG_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPD_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (CART_ID, USER_ID),
	FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
 );

 CREATE TABLE PAYMENT (
 	PAYMENT_ID INT(10) AUTO_INCREMENT,
 	USER_ID INT(10),
	GOODS_ID INT(10),
	GOODS_DETAIL_ID INT(10),
	REG_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPD_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PAYMENT_ID)
 );